version: 2
updates:
  # Maintain the requirements in the github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - JoranAngevaare

  # Maintain the requirements requirements folder
  - package-ecosystem: "pip"
    directory: "/extra_requirements"
    schedule:
      interval: "hourly"
    target-branch: "master"
    open-pull-requests-limit: 30
    assignees:
      - JoranAngevaare

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "hourly"
    target-branch: "master"
    assignees:
      - JoranAngevaare

