version: 2
updates:
  # Maintain the requirements in the github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - JoranAngevaare

#   - package-ecosystem: "pip"
#     directory: "/extra_requirements"
#     schedule:
#       interval: "daily"
#     target-branch: "master"
#     assignees:
#       - JoranAngevaare

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    assignees:
      - JoranAngevaare

