# Auto approve dependabot updates if it passes the tests

name: Auto approve
on:
  workflow_dispatch:
  pull_request:
    types: [ opened ]

jobs:
  build:
    name: Auto approve
    runs-on: ubuntu-latest
    steps:
      - uses: derekprior/add-autoresponse@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          respondableId: ${{ github.event.pull_request.node_id }}
          response: "@dependabot squash and merge"
          author: "JoranAngevaare"
