name: Test package

# Trigger this code when a new release is published
on:
  workflow_dispatch:
  release:
    types: [ created ]
  pull_request:
  push:
    branches:
      - master

jobs:
  update:
    name: "$py_${{ matrix.python-version }} (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: False
      matrix:
        os: [ "ubuntu-latest" , "macos-latest"]
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10"]
    steps:
      # Setup and installation
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip install -r extra_requirements/requirements-tests.txt
